### ISSUE TITLE
ImportError: cannot import name '_native_macos_obs' from partially initialized module 'pyvirtualcam' on macOS

### ISSUE THREAD

**Issue by rickwierenga** [letmaik/pyvirtualcam#98]
- Operating system: macOS
- Python version: 3.10.6
- pyvirtualcam version: latest (installed from source)
- Virtual camera (OBS, v4l2loopback, UnityCapture): OBS
- Virtual camera version: 28.0.3

**Describe the bug**

```python
>>> import pyvirtualcam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rickwierenga/workspace/nomoremeetings/pyvirtualcam/pyvirtualcam/__init__.py", line 3, in <module>
    from .camera import Camera, PixelFormat, Backend, register_backend
  File "/Users/rickwierenga/workspace/nomoremeetings/pyvirtualcam/pyvirtualcam/camera.py", line 112, in <module>
    from pyvirtualcam import _native_macos_obs
ImportError: cannot import name '_native_macos_obs' from partially initialized module 'pyvirtualcam' (most likely due to a circular import) (/Users/rickwierenga/workspace/nomoremeetings/pyvirtualcam/pyvirtualcam/__init__.py)
```

**Comment by letmaik** [comment]
This is a normal behaviour of Python. You need to change the current directory to some other directory to avoid it picking up the package from the source folder instead of the installed package.
